repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.2.3
        hooks:
        - id: trailing-whitespace

    -   repo: https://github.com/python/black
        rev: 19.3b0
        hooks:
        - id: black
          language_version: python3.7

    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v1.5.0
        hooks:
        - id: reorder-python-imports

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.710
        hooks:
        - id: mypy
