# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- task: NodeTool@0
  inputs:
    versionSpec: '10.13.0'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install -r api/requirements.txt
  displayName: 'Install requirements'

- script: cd client && npm i
  displayName: 'Install client packages'

- script: npm i -g tslint typescript tslib
  displayName: 'Install global npm packages for pre-commit use'

- script: pre-commit run --all-files --show-diff-on-failure
  displayName: run pre-commit

- script: pytest api/tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- script: npm run build
  displayName: 'Build client deploy files'

- script: cd client && now --token $ZEIT_TOKEN --scope $ZEIT_TEAMNAME --prod
  displayName: 'Deploy client to Zeit now'

- script: cd api && now --token $ZEIT_TOKEN --scope $ZEIT_TEAMNAME --prod
  displayName: 'Deploy api to Zeit now'


