version: '3.7'

services:
  api:
    container_name: sc-api
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/usr/src/app
    env_file: ./api/.env
    ports:
      - 8000

  web:
    container_name: sc-client
    build:
      context: ./client
      dockerfile: Dockerfile.web
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - 3000
      - 3001:3001
    env_file: ./client/.env

  db:
    container_name: sc-db
    image: postgres:11.4-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saveclub_db

  proxy:
    container_name: sc-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
