version: '3.7'

services:

  api:
    build:
      context: api
    container_name: api
    image: saveclub/api

  web:
    build:
      context: client
    container_name: web
    image: saveclub/web

  db:
    container_name: db
    image: mdillon/postgis:11

  proxy:
    container_name: proxy
    image: saveclub/proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
