version: '3.7'

services:
  api:
    container_name: sc-api
    depends_on:
      - db
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    environment:
      VIRTUAL_HOST: api.lvh.me
      VIRTUAL_PORT: 8000
      PORT: 8000
      DATABASE_URL: postgres://postgres:postgres@db:5432/saveclub_db?connect_timeout=60
      ENVIRONMENT: DEVELOPMENT
      SECRET_KEY: b'\xec\xe5\xb7WCg\xaf\xc9\xf5\xfam\xaa\x12\xbd\xc7\x02'
    ports:
      - 8000

  web:
    container_name: sc-client
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - 3000
      - 3001:3001
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: lvh.me
      VIRTUAL_PORT: 3000
      API_URL: api.lvh.me

  db:
    container_name: sc-db
    image: postgres:11.4-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saveclub_db

  proxy:
    container_name: sc-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
