version: '3.7'

services:

  api:
    build:
      context: api
    container_name: sc-api
    image: saveclub/api

  web:
    build:
      context: client
    container_name: sc-client
    image: saveclub/web

  proxy:
    container_name: sc-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
